### ISSUE TITLE
Primeiro encontro BeerJS Recife - 16/03/2017

### ISSUE THREAD

**Issue by victorlaerte** [beerjs/recife#2]
O primeiro encontro do BeerJS Recife irá acontecer no dia 16 de março de 2017 às 19:00 no Apolo Café.
Sinta-se a vontade para convidar seus amigos e bater um bate papo informal sobre JS e tecnologias em geral.

**Comment by interaminense** [comment]
![](http://beerjs.github.io/recife/img/events/beerjsrecife1.jpeg)

**Comment by interaminense** [comment]
![](http://beerjs.github.io/recife/img/events/beerjsrecife2.JPG)
